"""Nonsecret approved isolated endpoints. No account keys or credentials."""
CONFIG = {
    "APP_ENV": "dev",
    "DEPLOYMENT_SCENARIO": "ecommerce",
    "AZURE_ENV_SCENARIO": "ecommerce",
    "AZURE_FOUNDRY_ENDPOINT": "https://aif-ccptu1feb0911.services.ai.azure.com/api/projects/proj-ccptu1feb0911",
    "AZURE_AI_AGENT_ENDPOINT": "https://aif-ccptu1feb0911.services.ai.azure.com/api/projects/proj-ccptu1feb0911",
    "AZURE_OPENAI_ENDPOINT": "https://aif-ccptu1feb0911.openai.azure.com/",
    "AZURE_OPENAI_DEPLOYMENT_NAME": "gpt-5.4-mini",
    "AZURE_AI_SEARCH_ENDPOINT": "https://srch-ccptu1feb0911.search.windows.net",
    "AZURE_SEARCH_ENDPOINT": "https://srch-ccptu1feb0911.search.windows.net",
    "AZURE_SEARCH_CATALOG_INDEX": "ptu-chatbot-products",
    "AZURE_SEARCH_PRODUCT_INDEX": "ptu-chatbot-products",
    "AZURE_SEARCH_POLICIES_INDEX": "ptu-chatbot-policies",
    "COSMOS_DB_ENDPOINT": "https://cosmos-ccptu1feb0911.documents.azure.com:443/",
    "COSMOS_DB_DATABASE_NAME": "ecommerce_db",
    "AZURE_COSMOSDB_DATABASE": "ecommerce_db",
    "FOUNDRY_CHAT_AGENT": "ptu-chatbot-chat-eval",
    "FOUNDRY_PRODUCT_AGENT": "ptu-chatbot-product-eval",
    "FOUNDRY_POLICY_AGENT": "ptu-chatbot-policy-eval",
    "ALLOWED_ORIGINS_STR": "http://127.0.0.1:5116,http://127.0.0.1:15116",
    "AZURE_BASIC_LOGGING_LEVEL": "WARNING",
    "AZURE_PACKAGE_LOGGING_LEVEL": "ERROR",
}
