<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ConsoleAOAI_Lab_VideoAnalyzer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ConsoleAOAI-Lab-VideoAnalyzer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\PromptsHelper.cs" Link="PromptsHelper.cs" />
    <Compile Include="..\VideosHelper.cs" Link="VideosHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20240616" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20240616" />
  </ItemGroup>

</Project>
